export default {
  STATES_GET_REQUEST: "STATES_GET_REQUEST",
  STATES_GET_RECEIVE: "STATES_GET_RECEIVE",
  STATES_GET_ERROR: "STATES_GET_ERROR",
  STATES_CLEAR: "STATES_CLEAR",
  STATES_CLEAR_ERROR: "STATES_CLEAR_ERROR",
  I18N_LANGUAGE: "I18N_LANGUAGE",
  I18N_LOCALE: "I18N_LOCALE"
};
